In [1]:
import numpy as np
def print_chess_board(positions):
    n = len(positions)
    board = [['.' for _ in range(n)] for _ in range(n)]
    
    for row in range(n):
        col = positions[row] - 1
        board[row][col] = 'Q'
    
    for row in board:
        print(' '.join(row))

In [2]:
def create_matrix(arr):
    size = len(arr)
    matrix = np.zeros((size, size), dtype=int)
    for i in range(size):
        matrix[i][arr[i]-1] = 1
    return matrix

arr = [1, 3, 6, 9, 7, 10, 4, 2, 5, 8]
result = create_matrix(arr)
print(result)

[[1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]]


In [3]:
positions = [1, 3, 6, 9, 7, 10, 4, 2, 5, 8]

print_chess_board(positions)

Q . . . . . . . . .
. . Q . . . . . . .
. . . . . Q . . . .
. . . . . . . . Q .
. . . . . . Q . . .
. . . . . . . . . Q
. . . Q . . . . . .
. Q . . . . . . . .
. . . . Q . . . . .
. . . . . . . Q . .


In [4]:
def is_valid(arr, pos, num):
    for i in range(pos):
        if arr[i] == num or abs(arr[i] - num) == abs(i - pos):
            return False
    return True

In [5]:
def solve_nqueens(arr, pos, i, solutions):
    n = len(arr)
    if pos == n:
        solutions.append(arr[:])  
        i += 1
        return i

    for num in range(1, n+1):
        if is_valid(arr, pos, num):
            arr[pos] = num
            i = solve_nqueens(arr, pos + 1, i, solutions)
            solutions.append(arr[:])
            i += 1
            arr[pos] = -1
    return i

In [8]:
arr = [-1] * 5

solutions = []
solve_nqueens(arr, 0, 1, solutions)

for i, solution in enumerate(solutions, start=1):
    print(i, " ", solution)

1   [1, 3, 5, 2, 4]
2   [1, 3, 5, 2, 4]
3   [1, 3, 5, 2, -1]
4   [1, 3, 5, -1, -1]
5   [1, 3, -1, -1, -1]
6   [1, 4, 2, 5, 3]
7   [1, 4, 2, 5, 3]
8   [1, 4, 2, 5, -1]
9   [1, 4, 2, -1, -1]
10   [1, 4, -1, -1, -1]
11   [1, 5, 2, -1, -1]
12   [1, 5, -1, -1, -1]
13   [1, -1, -1, -1, -1]
14   [2, 4, 1, 3, 5]
15   [2, 4, 1, 3, 5]
16   [2, 4, 1, 3, -1]
17   [2, 4, 1, -1, -1]
18   [2, 4, -1, -1, -1]
19   [2, 5, 1, 4, -1]
20   [2, 5, 1, -1, -1]
21   [2, 5, 3, 1, 4]
22   [2, 5, 3, 1, 4]
23   [2, 5, 3, 1, -1]
24   [2, 5, 3, -1, -1]
25   [2, 5, -1, -1, -1]
26   [2, -1, -1, -1, -1]
27   [3, 1, 4, 2, 5]
28   [3, 1, 4, 2, 5]
29   [3, 1, 4, 2, -1]
30   [3, 1, 4, -1, -1]
31   [3, 1, -1, -1, -1]
32   [3, 5, 2, 4, 1]
33   [3, 5, 2, 4, 1]
34   [3, 5, 2, 4, -1]
35   [3, 5, 2, -1, -1]
36   [3, 5, -1, -1, -1]
37   [3, -1, -1, -1, -1]
38   [4, 1, 3, 5, 2]
39   [4, 1, 3, 5, 2]
40   [4, 1, 3, 5, -1]
41   [4, 1, 3, -1, -1]
42   [4, 1, 5, 2, -1]
43   [4, 1, 5, -1, -1]
44   [4, 1, -1, -1, -1]
45   [4, 2, 5, 3, 1]

In [9]:
def clean(solutions):
    n = len(solutions)
    i = 1
    while i < len(solutions) :
        current_solution = solutions[i]
        previous_solution = solutions[i - 1]

        if all(current_solution[j] == -1 or current_solution[j] == previous_solution[j] for j in range(len(current_solution))):
            solutions.pop(i)
        else:
            i += 1

clean(solutions)

for i, solution in enumerate(solutions, start=1):
    print(i, " ", solution)

1   [1, 3, 5, 2, 4]
2   [1, 4, 2, 5, 3]
3   [1, 5, 2, -1, -1]
4   [2, 4, 1, 3, 5]
5   [2, 5, 1, 4, -1]
6   [2, 5, 3, 1, 4]
7   [3, 1, 4, 2, 5]
8   [3, 5, 2, 4, 1]
9   [4, 1, 3, 5, 2]
10   [4, 1, 5, 2, -1]
11   [4, 2, 5, 3, 1]
12   [5, 1, 4, -1, -1]
13   [5, 2, 4, 1, 3]
14   [5, 3, 1, 4, 2]
